config/routes.rb
Rails.application.routes.draw do
#  get 'home/index'
    match "/index" , to:  "home#index", via: :GET
    match "/tweets",  to: "home#tweet_form",  via: :GET
    match "/load", to: "home#load_tweets", via: :POST
    match "/display" , to: "home#score_search", via: :GET
    
end

app/models/tweet.rb
require 'sentiments'
class Tweet
  include Mongoid::Document
   


  field :text,      type: String
  field :sentiment, type: String 
  CONFIG = {:consumer_key=>"BIH1an9uUvcLuz4n8nzTId9rR", :consumer_secret=>"678HNHv3MSFhwjbJoYS2XDZ4z7YHnBsUISJ9gvvem1mKioQ3t5"} 
     
    
    
    def self.pull_tweets hashtag
        client = Twitter::REST::Client.new(CONFIG)
        raw_results = client.search(hashtag)
        #need to convert raw_results to hash
        conv_result_to_hash = raw_results.to_h
        
        
        #########################################################################################################################
        refined_results = conv_result_to_hash[:statuses].collect{|r| r[:text]} 
        tweets_array = refined_results.to_a
        tweets_array.each {|tweet_text| Tweet.create! :text => tweet_text , :sentiment => sentiments.score(tweet_text)["pos"].round(1) }
        end
            
        #########################################################################################################################
        

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index 
    @tweets = Tweet.all.to_a
    end
    
    def tweet_form
    end
    
    def load_tweets
    @load_tweets = Tweet.pull_tweets(params[:hashtag])    
    end
    
    def score_search
        p params
        p ".................................."
      
    #@show_tweet = Tweet.where(params[:sentiment] => :score ).to_a 
    #@show_tweet = Tweet.where(sentiment: params[:sentiment]).to_a
    #@show_tweet = Tweet.where(sentiment: 0.5)
    @show_tweet = Tweet.where(:sentiment => params[:sentiment])
    #@show_tweet = Tweet.where(params[:sentiment] => params[:score.to_s])    
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Index /Tweets </h1>

<%@tweets.each do |show_tweet|%>
<p><b>Tweet ID: </b> <%=show_tweet["_id"]%>, <b>Tweet text: </b> <%=show_tweet["text"] %>, <b>Tweet Positivity Score: </b><%=show_tweet["sentiment"]%> </p>
<br/><br/>
<% end %>

<footer>
<p><b>Current Tweet Count: 
    <%= Tweet.count %>
</b>    
</p>
<%= link_to "Go to Search", tweets_path %>
</footer>

app/views/home/load_tweets.html.erb
<h1> Your Search Results: </h1>

<li><%= link_to "Back to Search" , tweets_path %></li>


<p>
<% @load_tweets.each do |disp| %>
    <%=disp%>
    
<br/><br/>
<p><b>Positivity Score of Tweet: <%= sentiments.score(disp)["pos"].round(1)%></b></p>
<br/>
<%end%>
</p>

<footer>
<b>Note:</b>
<ul>Positive Sentiment Score is based on a 0-1 scale with <b>"0"</b> being the <b>lowest</b> and <b>"1"</b> being the <b>highest</b>.</ul>
</footer>

app/views/home/score_search.html.erb
<h1>Displaying Query Results</h1>
<br/>

<% @show_tweet.each do |display|%>
<%= display.to_a %>
<br/><br/>

<%end%>

app/views/home/tweet_form.html.erb
<ol>
<h4>Use This To Search For Particular Hashtags</h4>
<li>  <%= form_tag("/load", method: "POST") do %>
  <%= label_tag(:hashtag, "Search for:") %>
  <%= text_field_tag(:hashtag) %>
  <%= submit_tag("Search") %>
<% end %>
</li>
<br/><br/>
<h4>Use This To Filter Tweets According to Sentiment Score</h4>  
<br/>
<li>
<%= form_tag("/display", method: "GET") do %>
  <%= label_tag(:sentiment, "Filter According to Sentiment Score:") %>
  <%= text_field_tag(:sentiment) %>
  <%= submit_tag("Search") %>
<% end %>
</li>    
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SentimentAnalysis2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>